apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0dh4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0049-tenant/tkrw-pr712-0075-0049-app/devfile-sample-0dh4@sha256:28a605a9fd6a17329623441d1cf0bb0c1d7b9b0b08b978fb15b1a8ff96a5b385
        name: my-nodejs
        resources: {}
status: {}
